# Generated by Django 4.2.3 on 2023-07-13 00:37

from django.db import migrations

def populate_status(apps, schemaeditor):
    entries = {
        "draft": "An unpublished post, not yet complete",
        "published": "A post being reviewed",
        "archived": "A archived post, not visible to end users"
    }
    Status= apps.get_model("posts", "Status")
    for name, desc in entries.items():
        status_obj = Status(name=name, description=desc)
        status_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_status_post_status'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
